package console_client;

import wsdl_autogenerated.Person;

import java.text.ParseException;
import java.util.List;

public class App {
    private static final String URL = "http://localhost:8080/rest/persons";

    public static void main(String[] args) throws ParseException {
        RestClient restClient = new RestClient();
        Person p = new Person();
        p.setName("Иван");
        p.setSurname("Иванов");
        Person p1 = new Person();
        p1.setName("Иван");
        p1.setSurname("Бабаев");

//        restClient.addPerson(p);
//        restClient.updatePerson(p, p1);
//        restClient.deletePerson(p);
        List<Person> list = restClient.getAllPersons("");
        for(Person e : list){
            System.out.println(e.toString());
        }
//        Client client = Client.create();
//        printList(getAllPersons(client, "Владимир"));
    }

}