package console_client;

import wsdl_autogenerated.Query;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class ConsoleInputReader {

    private String readNum(BufferedReader reader, String message) throws IOException{
            System.out.println(message);
            String age = reader.readLine();
            if(age.equals("")) return age;
            else {
                try {
                    Integer.parseInt(age);
                    return age;
                } catch (NumberFormatException e) {
                    System.out.println("Число некорректно!");
                    return readNum(reader, message);
                }
            }
    }

    public Query readInput() {
        Query query = new Query();
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
            query.setId(readNum(reader, "Enter ID: "));
            System.out.println("Enter name: ");
            query.setName(reader.readLine());
            System.out.println("Enter surname: ");
            query.setSurname(reader.readLine());
            query.setAge(readNum(reader, "Enter age: "));
            System.out.println("Enter country: ");
            query.setCountry(reader.readLine());
            System.out.println("Enter gender: ");
            query.setGender(reader.readLine());
            return query;
        }
        catch (IOException e) {
            System.out.println(e.toString());
        }
        return query;
    }
}
