package console_client;


import cat_service.CatImage;
import cat_service.CatImageService;
import cat_service.FileDownload;
import com.sun.xml.internal.ws.developer.JAXWSProperties;
import com.sun.xml.internal.ws.developer.StreamingDataHandler;

import javax.activation.DataHandler;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.soap.MTOMFeature;
import java.io.File;
import java.util.Map;
import java.util.logging.Logger;

public class WebServiceClient {

    private final static Logger log = Logger.getLogger(WebServiceClient.class.getName());

    public static void main(String[] args) {
        CatImageService catImageService = new CatImageService();
        MTOMFeature feature = new MTOMFeature();
        CatImage port = catImageService.getCatImagePort(feature);
        StreamingDataHandler streamDataHandler = (StreamingDataHandler)port.fileDownload();;
        try{
            File file = new File("./cat.jpg");
            streamDataHandler.moveTo(file);
            streamDataHandler.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
  }

//    public static void main(String[] args) throws MalformedURLException {
//        try {
//            URL url = new URL("http://localhost:8080/PersonService?wsdl");
//            wsdl_autogenerated.PersonService personService = new PersonService(url);
//            OperationHandler operationHandler = new OperationHandler(personService);
//            operationHandler.operationSelectDialog();
//        } catch (ServerException | SOAPFaultException sfe){
//            System.out.println("Server returned error: " + sfe.getMessage());
//        }
//    }


}
