package console_client;

import wsdl_autogenerated.PersonService;

import javax.xml.ws.WebServiceException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

public class WebServiceClient {

    private final static Logger log = Logger.getLogger(WebServiceClient.class.getName());


    public static void main(String[] args) throws MalformedURLException {
        try {
            URL url = new URL("http://localhost:8080/PersonService?wsdl");
            wsdl_autogenerated.PersonService personService = new PersonService(url);
            OperationHandler operationHandler = new OperationHandler(personService);
            operationHandler.operationSelectDialog();
        }catch (WebServiceException e){
            log.log(Level.SEVERE, "Exception: ", e);
            log.log(Level.SEVERE, "Error! WSDL server not started or unavailable!");
        }
    }


}
