package console_client;

import wsdl_autogenerated.Person;
import wsdl_autogenerated.PersonArray;
import wsdl_autogenerated.PersonService;
import wsdl_autogenerated.Query;

import javax.xml.ws.WebServiceException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class WebServiceClient {

    private final static Logger log = Logger.getLogger(WebServiceClient.class.getName());

    public static void main(String[] args) throws MalformedURLException {
        try {
            URL url = new URL("http://localhost:8080/PersonService?wsdl");
            wsdl_autogenerated.PersonService personService = new PersonService(url);
        ConsoleInputReader inputReader = new ConsoleInputReader();
        Query query = inputReader.readInput();
        PersonArray persons = personService.getPersonWebServicePort().selectPersonsByQueryClass(query);
        for (Person person : persons.getItem()) {
            System.out.println("name: " + person.getName() +
                    ", surname: " + person.getSurname() + ", age: " + person.getAge() +
                    ", country: " + person.getCountry()+ ", gender: " + person.getGender());
        }
        System.out.println("Total persons: " + persons.getItem().size());
        }
        catch (WebServiceException e){
            log.log(Level.SEVERE, "Exception: ", e);
            log.log(Level.SEVERE, "Error! WSDL server not started or unavailable!");
        }
    }
}
