
package wsdl_autogenerated;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://web_services/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web_services/PersonWebService/insertPersonByQueryClassRequest", output = "http://web_services/PersonWebService/insertPersonByQueryClassResponse")
    public String insertPersonByQueryClass(
        @WebParam(name = "arg0", partName = "arg0")
        Query arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web_services/PersonWebService/updatePersonByQueryClassRequest", output = "http://web_services/PersonWebService/updatePersonByQueryClassResponse")
    public String updatePersonByQueryClass(
        @WebParam(name = "arg0", partName = "arg0")
        Query arg0,
        @WebParam(name = "arg1", partName = "arg1")
        Query arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsdl_autogenerated.PersonArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web_services/PersonWebService/selectPersonsByQueryClassRequest", output = "http://web_services/PersonWebService/selectPersonsByQueryClassResponse")
    public PersonArray selectPersonsByQueryClass(
        @WebParam(name = "arg0", partName = "arg0")
        Query arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web_services/PersonWebService/deletePersonByQueryClassRequest", output = "http://web_services/PersonWebService/deletePersonByQueryClassResponse")
    public String deletePersonByQueryClass(
        @WebParam(name = "arg0", partName = "arg0")
        Query arg0);

    /**
     * 
     * @return
     *     returns wsdl_autogenerated.PersonArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://web_services/PersonWebService/getPersonsRequest", output = "http://web_services/PersonWebService/getPersonsResponse")
    public PersonArray getPersons();

}
