package console_client;

import wsdl_autogenerated.Person;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class ConsoleInputReader {

    private int readNum(BufferedReader reader, String message) throws IOException{
            System.out.println(message);
            String age = reader.readLine();
            if(age.equals("")) return -1;
            else {
                try {
                    return Integer.parseInt(age);
                } catch (NumberFormatException e) {
                    System.out.println("Number is incorrect!");
                    return readNum(reader, message);
                }
            }
    }

    public Person readInsertInput() {
        Person query = new Person();
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
            System.out.println("Enter name: ");
            query.setName(reader.readLine());
            System.out.println("Enter surname: ");
            query.setSurname(reader.readLine());
            query.setAge(readNum(reader, "Enter age: "));
            System.out.println("Enter country: ");
            query.setCountry(reader.readLine());
            System.out.println("Enter gender: ");
            query.setGender(reader.readLine());
            return query;
        }
        catch (IOException e) {
            System.out.println(e.toString());
        }
        return query;
    }

    public Person readSearchInput() {
        Person query = new Person();
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
            query.setId(readNum(reader, "Enter ID: "));
            System.out.println("Enter name: ");
            query.setName(reader.readLine());
            System.out.println("Enter surname: ");
            query.setSurname(reader.readLine());
            query.setAge(readNum(reader, "Enter age: "));
            System.out.println("Enter country: ");
            query.setCountry(reader.readLine());
            System.out.println("Enter gender: ");
            query.setGender(reader.readLine());
            return query;
        }
        catch (IOException e) {
            System.out.println(e.toString());
        }
        return query;
    }
}
