
package cat_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CatImageService", targetNamespace = "http://web_services/", wsdlLocation = "http://localhost:8080/CatImageService?wsdl")
public class CatImageService
    extends Service
{

    private final static URL CATIMAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException CATIMAGESERVICE_EXCEPTION;
    private final static QName CATIMAGESERVICE_QNAME = new QName("http://web_services/", "CatImageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CatImageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATIMAGESERVICE_WSDL_LOCATION = url;
        CATIMAGESERVICE_EXCEPTION = e;
    }

    public CatImageService() {
        super(__getWsdlLocation(), CATIMAGESERVICE_QNAME);
    }

    public CatImageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATIMAGESERVICE_QNAME, features);
    }

    public CatImageService(URL wsdlLocation) {
        super(wsdlLocation, CATIMAGESERVICE_QNAME);
    }

    public CatImageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATIMAGESERVICE_QNAME, features);
    }

    public CatImageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatImageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CatImage
     */
    @WebEndpoint(name = "CatImagePort")
    public CatImage getCatImagePort() {
        return super.getPort(new QName("http://web_services/", "CatImagePort"), CatImage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatImage
     */
    @WebEndpoint(name = "CatImagePort")
    public CatImage getCatImagePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web_services/", "CatImagePort"), CatImage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATIMAGESERVICE_EXCEPTION!= null) {
            throw CATIMAGESERVICE_EXCEPTION;
        }
        return CATIMAGESERVICE_WSDL_LOCATION;
    }

}
